<section>
    <div class="decade">
      <a href="">1989 / 1999</a>
      <a href="">1999 / 2009</a>
      <a href="">2009 / 2019</a>
    </div>
    <div class="timeline">
        <h2>Dates clés</h2>
        <h3>Un évènement marquants par année</h3>

        <ul>
          <li><a href=""><span>1989</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1990</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1991</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1992</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1993</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1994</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1995</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1996</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
          <li><a href=""><span>1997</span></a><div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates a ut incidunt quidem laborum soluta molestias quis odio animi velit officiis, exercitationem aspernatur laudantium unde provident debitis reiciendis? Eveniet, libero.</div></li>
        </ul>
    </div>
  </section>